### PR TITLE
Calculate ww3_bounc geographic distances with haversines and utilize verbose=2 output

### LINKED ISSUE #1344: Non-unique nearest point calculation in ww3_bounc
**Describe the bug**
When assigning  NetCDF spectra to input boundary nodes (MAPSTA=2, assigned via INBND_NML in ww3_grid.nml), ww3_bounc uses an iterative method to identify the two nearest neighbor spectra in spec.list. Custom diagnostic output in ww3_bounc reveals that points even one kilometer apart can be calculated as having a separation distance of zero. Moreover, some input point - boundary point pairs result in a returned distance of NaN. As a result, assignment of spectra to boundary nodes is sensitive to the ordering of the boundary nodes and to the ordering of the provided spectra in a manner that is not explicit in the code.

**To Reproduce**
1. Run ww3_grid
2. Provide multiple spectra that are within one kilometer of a boundary input node via files itemized in spec.list.
3. Run ww3_bounc

**Expected behavior**
Only one input spectrum is identified as having a minimum distance from each boundary node when using a grid/mesh with reasonable resolution.

**Screenshot of the issue**
image

**Additional context**
The screenshot consists of custom diagnostic output in ww3_bounc. Columns (labeled) are:
1. Boundary node index (outer loop)
2. Input spectrum file index (inner loop)
3. Distance in longitude between the boundary node and the input spectrum file
4. Distance in latitude between the boundary node and the input spectrum file
5. Total distance as calculated by DIST_SPHERE
6. Minimum distance from the boundary node to all input spectrum files (so far)
7. 2nd shortest distance from the boundary node to all input spectrum files (so far)

Note the presence of multiple locations with zero and NaN values for distance despite meridional and zonal distances (0.001-0.01 deg) that can reasonably be found along the boundaries of coastal grids/meshes. The example provided is at a location near the USACE FRF in Duck, North Carolina, USA (-75.7513, 36.1821).

**Proposed fix**
Calculate geographic distances with an updated formula that employs haversines. Haversine-based great-arc distances are more robust both to small angles and to floating point errors that can produce arccos arguments that are larger than one (and hence imaginary results). This fix, along with the additional lines of diagnostic stdout, is employed in a new branch in erdc/WW3, The screenshot below demonstrates the expected behavior.

**Screenshot of the proposed fix**
image

### PR DESCRIPTION
**Pull request by dahonegger**
# Pull Request Summary
Bug fix for [#1344](https://github.com/NOAA-EMC/WW3/issues/1344)

## Description
When assigning NetCDF spectra to input boundary nodes, ww3_bounc uses an iterative method to identify the two nearest neighbor spectra in spec.list. Custom diagnostic output in ww3_bounc reveals that points even one kilometer apart can be calculated as having a separation distance of zero. Moreover, some input point - boundary point pairs result in a returned distance of NaN. As a result, assignment of spectra to boundary nodes is sensitive to the ordering of the boundary nodes and to the ordering of the provided spectra in a manner that is not explicit in the code.

This fix replaces usage of DIST_SPHERE in [ww3_bounc](model/src/ww3_bounc.F90) with a new function, DIST_HAVERSINE, that is more robust when distances are on the order of 1 km or less. Both DIST_SPHERE and DIST_HAVERSINE are defined in [w3servmd](model/src/w3servmd.F90).

This fix additionally includes the option for more detailed diagnostic output from ww3_bounc that is triggered with the VERBOSE=2 namelist value in ww3_bounc.nml.

There are expected changes to regression tests [tp2.8](regtests/ww3_tp2.8) and [tp2.17](regtests/ww3_tp2.17) owing to modifications to the weight assignments of the linearly interpolated boundary spectra. 

### Issue(s) addressed

- Fixes [#1344](https://github.com/NOAA-EMC/WW3/issues/1344)

### Commit Message

Calculate ww3_bounc geographic distances with haversines and utilize verbose=2 output

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

```
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (4 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (3 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (5 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.17/./work_ma                     (1 files differ)
ww3_tp2.17/./work_mc1                     (1 files differ)
ww3_tp2.17/./work_mb                     (1 files differ)
ww3_tp2.17/./work_mc                     (1 files differ)
ww3_tp2.17/./work_ma1                     (1 files differ)
ww3_tp2.17/./work_a                     (1 files differ)
ww3_tp2.17/./work_c                     (1 files differ)
ww3_tp2.17/./work_b                     (1 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_tp2.8/./work_PR3_UQ                     (4 files differ)
```

* How were these changes tested? **Via matrix**
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) **Tests that use ww3_bounc with FLAGLL=.true. cover the changes, but the newly utilized VERBOSE=2 value in ww3_bounc.nml is not tested.**
* Have the matrix regression tests been run (if yes, please note HPC and compiler)? **Yes, on an ERDC HPC with Intel**
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.) **Expected changes to the regression tests include: modifications to the weight assignments of the linearly interpolated boundary spectra.**
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

[matrixCompSummary.txt](https://github.com/user-attachments/files/19235974/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/user-attachments/files/19235976/matrixDiff.txt)
[matrixCompFull.txt](https://github.com/user-attachments/files/19235977/matrixCompFull.txt)

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
Thank you for submitting this fix @dahonegger.  We will start looking at it and I'll reply back tomorrow with the CM assigned and the timeline.

**Comment by mickaelaccensi** [comment]
Thank you David for this improvement !

**Comment by MatthewMasarik-NOAA** [comment]
@dahonegger I spoke with @JessicaMeixner-NOAA offline and we will be assigning a CM on Monday when @sbanihash is back from leave.  We will be back in touch then.  Thank you again for this submission.

**Comment by sbanihash** [comment]
Thank you @dahonegger for your work on this fix. I would like to request @kestonsmith-noaa to take a look at this PR and review the changes. Either @JessicaMeixner-NOAA or I would also take a look as a second reviewer as well.

File: model/src/w3servmd.F90 [hunk 1]
```diff
@@ -511,6 +512,100 @@ REAL FUNCTION EJ5P ( F, ALFA, FP, YLN, SIGA, SIGB )
...
+    !  9. Switches :
+    !
+    !     None.
+    !
+    ! 10. Source code :
+    !
+    !/ ------------------------------------------------------------------- /
+    USE CONSTANTS
+    ! DERA: Degrees to Radians (PI/180)
+    ! RADE: Radius of the Earth
```
Comment (sbanihash) [inline model/src/w3servmd.F90]: If this is intended to be Radius of the Earth , the constants module does not define it that way. Here is what RADE is in constants.F90: 
REAL, PARAMETER :: RADE = 180. / PI !< RADE Conversion factor from radians to degrees

File: model/src/w3servmd.F90 [hunk 2]
```diff
@@ -511,6 +512,100 @@ REAL FUNCTION EJ5P ( F, ALFA, FP, YLN, SIGA, SIGB )
...
+    !/ Local parameters
+    !/
+    REAL                    :: DLON, DLAT, A, C 
+    !/
+    !/ ------------------------------------------------------------------- /
+    !/
+    
+    ! Compute differences in latitude and longitude
+    DLAT = (LAT2 - LAT1) * DERA
+    DLON = (LON2 - LON1) * DERA
```
Comment (sbanihash) [inline model/src/w3servmd.F90:594]: Should we make sure LAT1, LAT2 are within [-90, 90] and LON1, LON2 are within [-180, 180] before computation?

**Comment by kestonsmith-noaa** [comment]
On the second point, checking coordinate range, I would prefer not to check
coordinate range within haversine, but rather at input.  Longitude and
latitude out of geographic range won't present numerical problems within
haversine and there are cases it may be useful to have longitudes outside
[-180,180], for instance in regional domains spanning the international
date line.   Best, Keston

**Comment by sbanihash** [comment]
> On the second point, checking coordinate range, I would prefer not to check coordinate range within haversine, but rather at input. Longitude and latitude out of geographic range won't present numerical problems within haversine and there are cases it may be useful to have longitudes outside [-180,180], for instance in regional domains spanning the international date line. Best, Keston

@kestonsmith-noaa Thank you for your input. I was thinking more about the DLON calculations (as opposed to a [0 360] coordinate), in order to make sure the  haversine of the central angle computation is correct. have to re-think to be honest. maybe it's not even important. Looking at the fact that the trigonometric functions involved are periodic, I think both coordinates should work.

File: model/src/w3servmd.F90 (hunk 1 above)
Comment (dahonegger) [reply model/src/w3servmd.F90]: Thank you @sbanihash for catching this oversight. I am correcting the variable description comment along with an aesthetic spacing adjustment in the header of ww3_bounc, and will push to this branch.

Comment (sbanihash) [reply model/src/w3servmd.F90]: @dahonegger I see your change and I am a bit confused. my understanding for the DIST_HAVERSINE = RADE * C on line 603 is that you would need to have the Radius of the earth right?

Comment (dahonegger) [reply model/src/w3servmd.F90]: @sbanihash I understand the confusion -- DIST_HAVERSINE is written to be a drop-in replacement for DIST_SPHERE, which calculates the angular distance (in degrees) between the two input locations. My now-corrected variable description for RADE was owing to an erroneous prior reading of DIST_SPHERE, in which I had interpreted RADE as "radius." Replacing RADE with RADIUS in either case will indeed produce the great-arc distance (in meters) instead.

Comment (sbanihash) [reply model/src/w3servmd.F90]: @dahonegger Thanks for the explanation, now I get it. Seems like no where in WAVEWATCH III we actually use the great-circle distance between the points anyways. Angular distance is what is being called in these routines as the expected output from DIST_SPHERE and with this addition in DIST_HAVERSINE as well.

**Review by sbanihash — APPROVED** [review]
Changes look good. Tests have been passed on Hera with expected changes in ww3_tp2.8 and tp_2.17.

**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (11 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (17 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (18 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.17/./work_b                     (1 files differ)
ww3_tp2.17/./work_mb                     (1 files differ)
ww3_tp2.17/./work_mc                     (1 files differ)
ww3_tp2.17/./work_a                     (1 files differ)
ww3_tp2.17/./work_ma1                     (1 files differ)
ww3_tp2.17/./work_c                     (1 files differ)
ww3_tp2.17/./work_ma                     (1 files differ)
ww3_tp2.17/./work_mc1                     (1 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_tp2.8/./work_PR3_UQ                     (8 files differ)
ww3_ufs1.3/./work_a                     (2 files differ)

[matrixCompSummary.txt](https://github.com/user-attachments/files/19441717/matrixCompSummary.txt)
[matrixCompFull.txt](https://github.com/user-attachments/files/19441718/matrixCompFull.txt)
[matrixDiff.txt](https://github.com/user-attachments/files/19441720/matrixDiff.txt)

**Comment by sbanihash** [comment]
@dahonegger Thank you for your work on this fix. I have approved your PR, just waiting for @kestonsmith-noaa to also confirm that the changes look good and I will then merge the PR. Thank for your patience.

**Comment by kestonsmith-noaa** [comment]
The changes looks fine to me. My only other suggestion would be to include the units of the return variable in the description, given our own internal confusion on this point and change of units within the function.   Something like:

    !  1. Purpose :
    !
    !     Computes the haversine distance between two points on a sphere in decimal degrees

**Comment by sbanihash** [comment]
Thank you @kestonsmith-noaa . That would be actually helpful.  @dahonegger would you mind making this small change? I can merge the PR afterwards. Thanks!

**Comment by aliabdolali** [comment]
Hi @sbanihash 
David is on AL until next week. You can either wait or add it to the header and merge.
Thanks for helping with the review.

**Comment by sbanihash** [comment]
> Hi @sbanihash David is on AL until next week. You can either wait or add it to the header and merge. Thanks for helping with the review.

Thanks @aliabdolali. Done!

**Comment by dahonegger** [comment]
Thanks all for the constructive feedback on this PR -- I wholeheartedly agree with the suggested modifications. 

And, thank you @aliabdolali for your help making sure @sbanihash was not left waiting for a response on Tuesday!
