### PR TITLE
Fix failure of restart reproducability in cases with variable water level and deep bathymetry.  

### LINKED ISSUE #1587: Potential non restart reproducibility when using variable water level in domains with deep water.
**Describe the bug**
Variable KDCHK in subroutine W3ULEV determines when WN and CG are recomputed due to depth changes.  Because this currently depends on total depth (DW=WLV - ZB), and only shallow regions have WN and CG recomputed when elevation changes, there is no practical way to precisely recover the values of WN and CG in deep water (where KDCHCK > KDMIN) from the cold start simulation at restart time.

**To Reproduce**
One way to manifest this bug is to add rising time varying sea level to regtest ww3_ufs1.1 (one must also introduce a restart to produce the bug).   

**Expected behavior**
Restarts from simulations described above will appear close but not be B4B replicas of the cold start.

**Screenshots**

**Additional context**
The problem can be remedied in a number of ways
(a) always recompute WN and CG in W3ULEV regardless of total depth
(b) Base KDCHK value on non varying bathymetric depth, ZB. In deep water (where KDCHCK > KDMIN) compute  WN and CG based on ZB rather than total depth - this would happen in subroutine w3init. In shallow water WN and CG would continue to depend on total depth and be computed in W3ULEV.
(c) Add WN and CG to restart files.

### PR DESCRIPTION
**Pull request by kestonsmith-noaa**
# Pull Request Summary
 

Changes are introduced to fix a bug affecting cases with variable water level and deep water bathymetry.  KDCHK is now based on bathymetric depth rather than total water level. In deep regions, CG and WN are not recomputed when water level changes, and their values are based on bathymetric depth rather than total water level. 

## Description

This PR addresses bug discussed in issue https://github.com/NOAA-EMC/WW3/issues/1587.  In the current develop code, KDCHK in subroutine W3ULEV is based on total water depth (WLV-ZB).  In the code introduced here, KDCHK is based only on bathymetric depth (-ZB) so that changes in water level do not effect whether or not WN and CG are recomputed when water level changes.  This code change allows restarts to remain bit for bit identical to the simulation they were restarted from. 

* Add any suggestions for a reviewer :  mingchen-NOAA
* Mention any labels that should be added:  _bug_

### Issue(s) addressed

fixes https://github.com/NOAA-EMC/WW3/issues/1587

### Commit Message

Fix failure of restart reproducability in cases with variable water level and deep bathymetry.  In subroutine W3ULEV KDCHK computed from bathymetric depth rather than total water level.  

### Check list  

- [X] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [X] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
A regression test illustrating the issue addressed here is introduced in PR 1589.

### Testing

* How were these changes tested?
regresion tests were run
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
A regression test illustrating the issue addressed here is introduced in PR 1589.
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
Yes, on Ursa with intel compiler
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)

* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

[matrixCompSummary.txt](https://github.com/user-attachments/files/26903805/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/user-attachments/files/26903809/matrixDiff.txt)
[matrixCompFull.txt](https://github.com/user-attachments/files/26903812/matrixCompFull.txt)

### CODE REVIEW

**Comment by kestonsmith-noaa** [comment]
I've brought this up to date with develop to include the regtest/ww3_tp2.17/input_deep[_restart] tests.  Differences in solution relative to develop are expected in regtest/ww3_tp2.17/work_deep_restart.  Solution in  regtest/ww3_tp2.17/work_deep_restart should be bit to bit with the solution in regtest/ww3_tp2.17/work_deep with PR#1591 but not current develop code.

**Comment by mingchen-NOAA** [comment]
@kestonsmith-noaa Thank you! I will start review and testing it.

File: model/src/w3initmd.F90 [hunk 1]
```diff
@@ -1399,7 +1402,23 @@ SUBROUTINE W3INIT ( IMOD, IsMulti, FEXT, MDS, MTRACE, ODAT, FLGRD,  FLGR2, FLGD,
...
+      ! Calculate the wavenumber for lowest frequency based on bathymetric depth
+      DEPTHbat=MAX(DMIN,-ZB(IS))
+#ifdef W3_PDLIB
+      CALL WAVNU3(SIG(1),DEPTHbat,WNbat,CGbat)
+#else
+      CALL WAVNU1(SIG(1),DEPTHbat,WNbat,CGbat)
+#endif
+      KDCHCK = WNbat * DEPTHbat
+      IF ( KDCHCK .GE. KDMAX ) THEN
+        ! Use time constant CG and WN based on bathymtry for this point rather than time varying total depth.
```
Comment (mingchen-NOAA) [inline model/src/w3initmd.F90]: typo: bathymetry

File: model/src/w3initmd.F90 [hunk 2]
```diff
@@ -1399,7 +1402,23 @@ SUBROUTINE W3INIT ( IMOD, IsMulti, FEXT, MDS, MTRACE, ODAT, FLGRD,  FLGR2, FLGD,
       WRITE (NDST,9051) IS, DEPTH
 #endif
       !
-      DO IK=0, NK+1
+      ! In shallow water, KDCHCK < KDMAX, assign time varying WN and CG as water level changes.
+      ! In deep water, KDCHCK >= KDMAX, assign time constant WN and CG based on bathymetric depth (-ZB).
+      !
+      ! Calculate the wavenumber for lowest frequency based on bathymetric depth
+      DEPTHbat=MAX(DMIN,-ZB(IS))
```
Comment (mingchen-NOAA) [inline model/src/w3initmd.F90]: Have you considered how DEPTHbat should be handled when IS=0?
In the original code, DEPTH is forced to DMIN when IS=0.
In `w3updtmd.F90`, `DEPTHbat=MAX(DMIN,-ZB(ISEA))` (https://github.com/NOAA-EMC/WW3/pull/1591/changes#diff-e2d241c332399a8d2f96e60a9c2159edc4154f60699b80fdd5a61ccd1a56164eR2354) is safe, b/c ISEA is looped from 1 to NSEA.

Comment (kestonsmith-noaa) [reply model/src/w3initmd.F90]: Yes, this is a good point.  I will change the code to reflect that.

Comment (kestonsmith-noaa) [reply model/src/w3initmd.F90]: OK code has been changed to address the typo and IS=0 case in w3init.  No changes apparent to previous version evident from running matrix13

**Comment by mingchen-NOAA** [comment]
Matrix comparison test against develop on Ursa Intel passed.
```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UNO_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.17/./work_deep_restart                     (32 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```

The changes in `ww3_tp2.17/./work_deep_restart                     (32 files differ)` are expected from this PR.

[matrixCompFull.txt](https://github.com/user-attachments/files/27050992/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/user-attachments/files/27050994/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/user-attachments/files/27050995/matrixDiff.txt)

**Comment by mingchen-NOAA** [comment]
Matrix comparison test against develop on Ursa GNU passed.
 
```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UNO_MPI_d2                     (11 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (18 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (18 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (11 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.17/./work_deep_restart                     (32 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (27 files differ)
```

The changes in `ww3_tp2.17/./work_deep_restart                     (32 files differ)` are expected from this PR.

[matrixCompFull.txt](https://github.com/user-attachments/files/27051051/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/user-attachments/files/27051053/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/user-attachments/files/27051054/matrixDiff.txt)

**Comment by mingchen-NOAA** [comment]
@kestonsmith-noaa FYI, I also checked `compare WAVEWATCH III ww3_tp2.17/work_deep and ww3_tp2.17/work_deep_restart` under `matrix13.out`, results are all identical for both Intel and GNU. Thank you for the update.

I will run matrix comparison tests against the PR branch itself to check the reproducibility. If they are passed, I will merge this PR.

**Comment by mingchen-NOAA** [comment]
Matrix comparison test against PR branch itself on Ursa Intel passed.

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UNO_MPI_d2                     (17 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (12 files differ)
mww3_test_03/./work_PR2_UQ_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_e_c                     (1 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (16 files differ)
mww3_test_03/./work_PR2_UNO_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (16 files differ)
mww3_test_03/./work_PR1_MPI_e                     (1 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (12 files differ)
mww3_test_03/./work_PR3_UNO_MPI_e_c                     (1 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (6 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (3 files differ)
```

[matrixCompFull.txt](https://github.com/user-attachments/files/27053712/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/user-attachments/files/27053713/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/user-attachments/files/27053714/matrixDiff.txt)

**Comment by mingchen-NOAA** [comment]
Matrix comparison test against PR branch itself on Ursa GNU passed.

```
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR3_UNO_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (6 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (13 files differ)
mww3_test_03/./work_PR2_UQ_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (15 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (15 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (10 files differ)
mww3_test_09/./work_MPI_ASCII                     (0 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (7 files differ)
ww3_tp2.16/./work_MPI_OMPH                     (5 files differ)
ww3_tp2.6/./work_ST4_ASCII                     (0 files differ)
ww3_ufs1.3/./work_a                     (27 files differ)
```

[matrixCompFull.txt](https://github.com/user-attachments/files/27053765/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/user-attachments/files/27053766/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/user-attachments/files/27053767/matrixDiff.txt)

**Comment by mingchen-NOAA** [comment]
All tests have been passed. The PR is ready to be merged.

**Review by mingchen-NOAA — APPROVED** [review]

**Comment by mingchen-NOAA** [comment]
@kestonsmith-noaa Your PR has been merged. Thank you very much for the updates!

**Comment by kestonsmith-noaa** [comment]
Great, Thanks for closing the related issue and catching that IS=0 problem.
