### PR TITLE
Netcdf parallel output extensions and bug repairs

### LINKED ISSUE #1366: Netcdf parallel output inconsistencies with WW3 binary output
**Describe the bug**
In the direct netcdf output the partitioned mean wave direction fields, PDIR, produces some numeric values where binary WW3 outputs not a number (NaN)  values.  This is the case across all partitions. Where binary WW3 output has numeric values they are equivalent to the values from the netcdf parallel output.

**To Reproduce**
Jessica Meixner has a test case that demonstrates the error at: https://github.com/jessicameixner-noaa/ufs-weather-model

**Expected behavior**
Running ww3_ounf on binary WW3 output should produce identical output to the netcdf parallel output, with
PDIR(:,:,1)  identical to pdir0(:), PDIR(:,:,2) identical to pdir1(:), etc.

**Screenshots**
None as of now

**Additional context**
The discrepancies in mean direction partition fields are due to a transformation from radians to degrees which does not check for NaN’s at application of the modulus function.  The discrepancy can be resolved with a small change to subroutine write_var3d.  Lines 613-615 of wav_history_mod.F90 (within subroutine write_var3d)
 
         if (mapsta(mapsf(isea,2),mapsf(isea,1)) > 0 )  then ! existing code
          varloc(:) = mod(630. - rade*varloc(:), 360.)
        end if

needs to account for NaN's in varloc (the mod function maps NaN's onto bogus numeric values).  So lines 613+ ... should be:

         if (mapsta(mapsf(isea,2),mapsf(isea,1)) > 0 )  then ! recommended change
          do k = 1, size(varloc,1)
           if (varloc(k) .ne. undef)  varloc(k) = mod(630. - rade*varloc(k), 360.)
          end do
        end if

This issue may be compiler or flag dependent (we used the intel fortran compiler in our test).   Jessica Meixner and I are going to continue to check other fields written directly to netcdf for inconsistencies with the binary WW3 output.

### PR DESCRIPTION
**Pull request by kestonsmith-noaa**
# Pull Request Summary
 

Repair bugs in netcdf parallel output and extend netcdf output capacity beyond original implementation. 

## Description

The proposed changes repair bugs in netcdf parallel output affecting partitioned direction(PDIR), friction velocity(UST), mean directional spread (THS), partitioned directional spread (PSI), and other variables.  Units are corrected for energy flux (CGE) and dynamic time step (DTDYN). 
 
Support is added for outputting wave number (WN). 

Frequency dimensions are added to the output as well, where output variables depend on frequency (EF and WN).

All changes are within file wav_history_mod.F90

Changes only affect coupled runs within ufs-weather-model at present.

* Add any suggestions for a reviewer 
 
Jessica Meixner
* Mention any labels that should be added:  _bug_, _documentation_, _enhancement_, _new feature_
 _bug_, _enhancement_

### Issue(s) addressed

Addresses: 
https://github.com/NOAA-EMC/WW3/issues/1366
 
Also has relevance to:
https://github.com/NOAA-EMC/WW3/issues/1401

### Commit Message

Fix bugs in netcdf parallel output and adds support for wave number and frequency dimensions in history output.

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
- [ ] Checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop). 
- [ ] If a version number update is required, checked the [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number) checklist. 
- [ ] If a new feature was added, a regression test for testing the new feature is added. 
 
### Testing

* How were these changes tested?
Changes were tested by comparing netcdf parallel output with binary output converted to netcdf with ww3_ounf.
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
No, regression tests which work with netcdf parallel output are needed to test the changes.
* Have the matrix regression tests been run (if yes, please note HPC and compiler)?
No
* Please indicate the expected changes in the regression test output, (Note the [list](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-develop#4-look-at-results) of known non-identical tests.)
None
* Please provide the summary output of matrix.comp (_matrix.Diff.txt_, _matrixCompFull.txt_ and _matrixCompSummary.txt_):

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@kestonsmith-noaa Can you change this PR to point to dev/ufs-weather-model instead of develop?

**Comment by kestonsmith-noaa** [comment]
Done. PR is now pointing to the correct branch.

**Comment by JessicaMeixner-NOAA** [comment]
Note this PR replaced https://github.com/NOAA-EMC/WW3/pull/1446

**Review by JessicaMeixner-NOAA — APPROVED** [review]

File: model/src/wav_history_mod.F90 [hunk 1]
```diff
@@ -317,10 +376,16 @@ subroutine write_history ( timen )
         if (vname .eq.   'USSPX') call write_var3d(iodesc3dp, vname, ussp     (1:nseal_cpl,   1:usspf(2)) )
         if (vname .eq.   'USSPY') call write_var3d(iodesc3dp, vname, ussp     (1:nseal_cpl,nk+1:nk+usspf(2)) )
 
+      else if (trim(outvars(n)%dims) == 'nk') then                           ! freq + 1 axis for wavenumber
+        var3d => var3dnk
+         if(vname .eq.       'WN') call write_var3d_transpose(iodesc3dnk, vname, wn (1:len_nk  ,1:nseal_cpl)   )
```
Comment (DeniseWorthen) [inline model/src/wav_history_mod.F90]: @kestonsmith-noaa Did you try simply sending ``transpose(wn)`` instead of creating a new routine etc?

**Comment by kestonsmith-noaa** [comment]
Hi Denise, As I recall, I did start there and ran into some difficulty.  I
will check later this afternoon and get back to you with a clearer answer
on why I abandoned that path. Best, Keston

File: model/src/wav_history_mod.F90 [hunk 2]
```diff
@@ -207,6 +230,18 @@ subroutine write_history ( timen )
...
+	     ierr = pio_def_var(pioid, 'freq_ef', PIO_DOUBLE, (/ktid/), varid)
+	     call handle_err(ierr,'def_freq')
+	     ierr = pio_put_att(pioid, varid, 'units', 's-1')
+      end if
+      if (nk_axis) then
+	     ierr = pio_def_var(pioid, 'freq_wn', PIO_DOUBLE, (/nktid/), varid)
+	     call handle_err(ierr,'def_freq')
+	     ierr = pio_put_att(pioid, varid, 'units', 's-1')
+      end if
+
```
Comment (DeniseWorthen) [inline model/src/wav_history_mod.F90:244]: Please fix the indenting on these lines (2-space indents for if-statements).

Also, is there a reason they are PIO_DOUBLE? They're just real(kind=4) values, correct?

**Comment by DeniseWorthen** [comment]
@kestonsmith-noaa Have you compiled and run in debug mode w/ the additional variable ``WN`` included in the output? I just did that test and it failed.

```
193: forrtl: severe (408): fort: (2): Subscript #2 of the array VAR has value 3674 which is greater than the upper bound of 3662
193:
193: Image              PC                Routine            Line        Source
193: fv3_s2sw.ks.db.ex  000000000146BD66  wav_history_mod_m         569  wav_history_mod.F90
193: fv3_s2sw.ks.db.ex  0000000001450B0E  wav_history_mod_m         381  wav_history_mod.F90
193: fv3_s2sw.ks.db.ex  0000000001F5862C  w3wavemd_mp_w3wav        2380  w3wavemd.F90
193: fv3_s2sw.ks.db.ex  0000000001426E83  wav_comp_nuopc_mp        1159  wav_comp_nuopc.F90
```

**Comment by kestonsmith-noaa** [comment]
Thanks Denise, I had not run this in debug mode with wavenumber output.
Unless you already see it I will try to find the issue tonight.  Best,
Keston

**Comment by DeniseWorthen** [comment]
I think the issue is that WN is global, and there doesn't seem to be an "extended array"

```
5:w3adatmd.F90:1326:    ALLOCATE ( WADATS(IMOD)%WN(0:NK+1,0:NSEA), STAT=ISTAT )
```

Once you fix the array size issue, please also try (in debug mode, with ``WN`` output included) and determine if you can use the existing var3d write routines if you call with  ``transpose(wn(1:nk,1:nsea))``

**Comment by kestonsmith-noaa** [comment]
I tried handling the wavenumber output with write_var3d on transpose(wn)... but the output is spatially incoherent- as if the indexing is randomized. This is true for both the structured and unstructured case.  The spatial noise in this output is different than the noise I mentioned in issue 1401(https://github.com/NOAA-EMC/WW3/issues/1401).  I understand regarding WN being a global variable, but the indexing doesn't seem to be consistent with this (at least the way the other global variables are indexed)- I'm sorry I don't have a more complete answer here.  I never dug deep enough into the binary output routines and ww3_ounf to determine where the problem is for the wn output there either- it also looks like an indexing issue, but not everywhere.   I've made a change to write_var3d_transpose to address the bug you found.  I am testing this presently.

**Comment by DeniseWorthen** [comment]
@kestonsmith-noaa I've been able to get what appears to be a sensible ``wn`` output field using this [branch](https://github.com/DeniseWorthen/WW3/tree/feature/fixstride0) using the existing var3d routine but sending w/ the transpose of ``wn``.  Note that branch also contains a couple of fixes I had been working on for the netcdf output.

This is 1e3*wn(k=1).

Screenshot 2025-08-20 at 2 54 00 PM

Output is here:
/scratch4/NCEPDEV/stmp/Denise.Worthen/RT_RUNDIRS/Denise.Worthen/FV3_RT/rt_1795368/pdlib.rundir

**Comment by kestonsmith-noaa** [comment]
Great! This looks consistent with the output I have.  Makes sense, we just need your "global" flag in var3d. How would you suggest we reconcile this?

**Comment by DeniseWorthen** [comment]
I would definitely prefer just using the existing var3d routine, transpose and the optional global flag. Could you just grab those changes from my branch ?

One weird thing is that I can't find your fork. If I try to compare my branch to yours, it doesn't give me your fork in the possible list of forks.

**Comment by kestonsmith-noaa** [comment]
I agree regarding jettisoning var3d_transpose.  I will set up my branch as
you suggest.I'm not sure what the issue is with the fork.  If it doesn't
mess up the PR I can make another fork off of dev/ufs-weather-model.

**Comment by DeniseWorthen** [comment]
Don't worry about the fork issue right now, it's just weird.

Regarding the binary, I suspect that the issue is in ``pdlib_field_vec`` and the ``do_output_exchanges``. I think there needs to be added code for the ``wn`` arrays.

**Comment by DeniseWorthen** [comment]
@kestonsmith-noaa Do you know if ``wn`` will be an output field for the GFSv17? If yes, then I think this needs to be tested with that mesh and on wcoss2 to ensure no unexpected behaviour.

**Comment by kestonsmith-noaa** [comment]
I suspect wn will not be an output in GFSv17 but that question should go to
@JessicaMeixner-NOAA for the definitive answer.

**Comment by JessicaMeixner-NOAA** [comment]
@kestonsmith-noaa @DeniseWorthen  - The output variables for GFSv17 are https://github.com/NOAA-EMC/global-workflow/blob/develop/dev/parm/config/gfs/config.wave#L92

**Comment by kestonsmith-noaa** [comment]
I replaced my write_var3d routine with Dennise's updated version and tested
the wn output with write_var3d (... transpose (wn...).  The result is the
same as I was getting previously and I believe it is correct.  Please
remember that these fields are inconsistent with the binary wn output.

I still need to modify the new write_var3d to prevent mapping NaN
directional values to incorrect field values rather than NaN, this is the
result of behavior of the mod function in:

          varloc(:) = mod(630. - rade*varloc(:), 360.)

File: model/src/wav_history_mod.F90 [hunk 3]
```diff
@@ -463,6 +534,87 @@ subroutine write_history ( timen )
...
+    end do
+
+    ierr = pio_inq_varid(pioid,  trim(vname), varid)
+    call handle_err(ierr, 'inquire variable '//trim(vname))
+    call pio_setframe(pioid, varid, int(1,kind=PIO_OFFSET_KIND))
+    call pio_write_darray(pioid, varid, iodesc, var3d, ierr)
+
+    deallocate(varloc)
+  end subroutine write_var3d
+
```
Comment (DeniseWorthen) [inline model/src/wav_history_mod.F90]: It looks like this routine got swapped in order w/ the var2d routine (ie, original order is routines var2d, then var3d), so it is appearing as a large difference. Please reorder var2d and var3d  so it is clear what changed in the var3d routine.

File: model/src/wav_history_mod.F90 [hunk 4]
```diff
@@ -372,8 +437,9 @@ subroutine write_history ( timen )
         if(vname .eq.      'PNR') call write_var2d(vname, pnr      (1:nseal_cpl) )
 
         ! Group 5
-        if (vname .eq.    'USTX') call write_var2d(vname, ust      (1:nseal_cpl)*asf(1:nseal_cpl), dir=cos(ustdir(1:nseal_cpl)), usemask='true')
-        if (vname .eq.    'USTY') call write_var2d(vname, ust      (1:nseal_cpl)*asf(1:nseal_cpl), dir=sin(ustdir(1:nseal_cpl)), usemask='true')
+        if (vname .eq.    'USTX') call write_var2d(vname, ust      (1:nsea)*asf(1:nsea), dir=cos(ustdir(1:nsea)), init0='false', global='true')
+        if (vname .eq.    'USTY') call write_var2d(vname, ust      (1:nsea)*asf(1:nsea), dir=sin(ustdir(1:nsea)), init0='false', global='true')
+
```
Comment (DeniseWorthen) [inline model/src/wav_history_mod.F90:441]: Have you run in debug mode and verified all the changed variables (ustx,usty, ths,psi) work as expected?

**Comment by kestonsmith-noaa** [comment]
Done.

**Comment by kestonsmith-noaa** [comment]
I corrected the handling of nan's for directional fields in write_var3d in
NetcdfNcPIOfixes.  This has been tested with partitioned direction output
(pdir) and passed.

File: model/src/wav_history_mod.F90 (hunk 2 above)
Comment (DeniseWorthen) [reply model/src/wav_history_mod.F90:244]: @kestonsmith-noaa Why are these axis values required to be double precision?

**Comment by kestonsmith-noaa** [comment]
Yes, there is no need for that. I think I was following the time dimension
output (which should be double).  I will switch those to real as well as
related mpi types if you would prefer.

**Comment by DeniseWorthen** [comment]
Unless they need to be double, I would use single.

**Comment by DeniseWorthen** [comment]
@kestonsmith-noaa Are you able to remove the tabs and the trailing whitespace in wav_history_mod.F90?

**Review by DeniseWorthen — APPROVED** [review]
@kestonsmith-noaa Thanks for removing the tabs; I think the whitespace might be harder, depending on which editor you're using.

**Comment by kestonsmith-noaa** [comment]
Yes, Should be all cleaned up now.  I think I've addressed all the issues
you raised and tested the netcdf vs binary output where relevant.  Please
let me know if you need anything else from my end.  Best, Keston

**Comment by gspetro-NOAA** [comment]
@kestonsmith-noaa Is there any reason to be concerned about the failing checks on this subcomponent PR? I see it's been approved but just wanted to be sure before we proceed with WM PR #2826.

**Comment by JessicaMeixner-NOAA** [comment]
@gspetro-NOAA  - are you talking about the CI tests in WW3?  

If so, then no - those are not concerning.  The CI has been broken for a while and does not reflect anything related to @kestonsmith-noaa's code.  I'll try to get that turned off if that's causing confusion.

**Comment by BrianCurtis-NOAA** [comment]
Are we bumping WW3 to the latest develop or keeping this hash specifically?

**Comment by JessicaMeixner-NOAA** [comment]
WW3's "develop" for UFS is dev/ufs-waether-model.  This PR should be a branch on top of dev/ufs-weather-model.  I will confirm now.

**Comment by BrianCurtis-NOAA** [comment]
> WW3's "develop" for UFS is dev/ufs-waether-model. This PR should be a branch on top of dev/ufs-weather-model. I will confirm now.

Yes, thanks! I realized that too late

**Comment by JessicaMeixner-NOAA** [comment]
Confirmed this branch is up to date w/dev/ufs-weather-model ... Always good to double check! Thanks @BrianCurtis-NOAA

**Comment by gspetro-NOAA** [comment]
Testing has successfully completed for WM PR [#2444](https://github.com/ufs-community/ufs-weather-model/pull/2444), so we can begin the merging process for this subcomponent PR.
